logging:
  level: INFO
  loggers:
    com.mailserver.manager: DEBUG
# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.cj.jdbc.Driver
    # the username
    user: root
    # the password
    #password: mysqlpswd
    password: skyline
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/automation
    properties:
            hibernate.dialect: org.hibernate.dialect.MySQLDialect
            hibernate.hbm2ddl.auto: create
